objects = ans_3_5.s ans_3_7.s ans_3_9.s ans_3_10.s ans_3_12.s \
					ans_3_16.s ans_3_17.s ans_3_18.s ans_3_20.s ans_3_21.s \
					ans_3_23.s ans_3_24.s ans_3_25.s ans_3_26.s ans_3_27.s \
					ans_3_28.s ans_3_29_1.s ans_3_29_2.s ans_3_31.s \


ans_3_5.s: ans_3_5.c
	gcc -Og -S ans_3_5.c

ans_3_7.s: ans_3_7.c
	gcc -Og -S ans_3_7.c

ans_3_9.s: ans_3_9.c
	gcc -Og -S ans_3_9.c

ans_3_10.s: ans_3_10.c
	gcc -Og -S ans_3_10.c

ans_3_12.s: ans_3_12.c
	gcc -Og -S ans_3_12.c

ans_3_16.s: ans_3_16.c
	gcc -Og -S ans_3_16.c

ans_3_17.s: ans_3_17.c
	gcc -Og -S ans_3_17.c

ans_3_18.s: ans_3_18.c
	gcc -Og -S ans_3_18.c

ans_3_20.s: ans_3_20.c
	gcc -Og -S ans_3_20.c

ans_3_21.s: ans_3_21.c
	gcc -Og -S ans_3_21.c

ans_3_23.s: ans_3_23.c
	gcc -Og -S ans_3_23.c

ans_3_24.s: ans_3_24.c
	gcc -Og -S ans_3_24.c

ans_3_25.s: ans_3_25.c
	gcc -Og -S ans_3_25.c

ans_3_26.s: ans_3_26.c
	gcc -Og -S ans_3_26.c

ans_3_27.s: ans_3_27.c
	gcc -Og -S ans_3_27.c

ans_3_28.s: ans_3_28.c
	gcc -Og -S ans_3_28.c

ans_3_29_1.s: ans_3_29_1.c
	gcc -Og -S ans_3_29_1.c

ans_3_29_2.s: ans_3_29_2.c
	gcc -Og -S ans_3_29_2.c

ans_3_31.s: ans_3_31.c
	gcc -Og -S ans_3_31.c

clean:
	rm $(objects)