objects = ans_3_5.s ans_3_7.s ans_3_9.s ans_3_10.s ans_3_12.s

ans_3_5.s: ans_3_5.c
	gcc -Og -S ans_3_5.c

ans_3_7.s: ans_3_7.c
	gcc -Og -S ans_3_7.c

ans_3_9.s: ans_3_9.c
	gcc -Og -S ans_3_9.c

ans_3_10.s: ans_3_10.c
	gcc -Og -S ans_3_10.c

ans_3_12.s: ans_3_12.c
	gcc -Og -S ans_3_12.c

clean:
	rm $(objects)